type: "reorder"

task: "frame-reorder"
dataset: "VideoReorder-MovieNet"

size_img: 224
size_txt: 32 
size_epoch: 20 
size_batch: 6 
lr: 1.2e-5
decay: 1e-3 
    
# path & dir
ckpt_path: "./_data/ckpt_violet_pretrain.pt"
dataset_dir : "/home/jianghui/dataset/VideoReorder-MovieNet/"
log_dir : "./outputs/log/"
checkpoint_dir : "./outputs/checkpoint/"

